version: '3.8'

services:
  app:
    build: .
    tty: true
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - .:/app

  mongodb:
    image: mongo:4.4
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'mongo --eval "db.runCommand({ connectionStatus: 1 })"']
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  mongodb_data: